### ISSUE TITLE
Don't save when there are no changes

### ISSUE THREAD

**Issue by lahwaacz** [s-weigand/jupyterlab_autosave_on_focus_change#51]
Currently the extension always saves the file when focus is changed, even when the editor does not hold anything unsaved. This always results in writes to disk and changed file modification timestamp, which is quite annoying.

**Comment by s-weigand** [comment]
Good point, saving should be lazy 👍

**Comment by s-weigand** [comment]
@all-contributors please add @lahwaacz for bug

**Comment by s-weigand** [comment]
@lahwaacz This should be fixed in [0.4.1](https://pypi.org/project/jupyterlab-autosave-on-focus-change/)

**Comment by lahwaacz** [comment]
@s-weigand Thank you! :tada:
